"""
Plan Tool
=========

Tool for generating execution plans by calling LLM.

This tool acts as a planning sub-agent that takes:
- objective: The goal to achieve
- available_tools: List of tools the agent can use
- trajectory (optional): History of [action, result] pairs
- previous_plan (optional): Previous plan for replan context

It then calls LLM to generate a structured plan based on the current situation.

Usage by Agent:
    {
        "tool": "plan",
        "params": {
            "objective": "Refactor the auth module and add error handling",
            "available_tools": ["read_file", "edit_file", "list_files", "message", "done"],
            "trajectory": [
                {"action": "list_files", "result": "Found auth.py, utils.py, config.py"},
                {"action": "read_file", "result": "Read auth.py (150 lines)"}
            ],
            "previous_plan": "1. List files\n2. Read auth.py\n3. Analyze code\n4. Refactor"
        }
    }

Returns:
    A plan string generated by LLM based on the inputs.
"""

from typing import Dict, Any, Optional, List, TYPE_CHECKING

if TYPE_CHECKING:
    pass  # For future type hints if needed
import logging
from tools.base import Tool, ToolResult, ToolContext, ToolMode, ExecutorType
from core.llm import get_llm_client
from core.config import config
# Note: OSS variant has no payments/credits system; we may optionally record usage.

logger = logging.getLogger(__name__)


# Planning prompt template
PLAN_SYSTEM_PROMPT = """You are the Planning Agent for Litewrite AI, a collaborative writing assistant specialized in document editing (LaTeX, Markdown, and other formats).

Your role is to analyze the current situation and create a plan for what to do NEXT. Focus only on upcoming steps - do not list what has already been done.

CONTEXT:
- Litewrite is a real-time collaborative document editor
- Users work with LaTeX papers, Markdown documents, and similar formats
- Tasks may involve writing, editing, formatting, research, citations, and document structure

PLANNING RULES:
1. Only output the NEXT steps to take - do not repeat completed actions
2. Steps can be high-level (e.g., "Analyze document structure") or specific actions
3. Not every step needs to map to a specific tool - use your judgment
4. Consider what has already been done (trajectory) to determine what comes next
5. Be practical and focused on achieving the user's writing goals
6. Keep plans concise - typically 2-5 steps

OUTPUT FORMAT:
Return a numbered list of upcoming steps. Be concise and actionable.

Example for adding a new section:
1. Write the introduction paragraph for the new section
2. Add supporting content and examples
3. Review and polish the section
4. Verify formatting is correct

Example for fixing an issue:
1. Analyze the issues in the problematic section
2. Apply the necessary corrections
3. Verify the changes"""


def build_plan_prompt(
    objective: str,
    available_tools: List[str],
    trajectory: Optional[List[Dict[str, str]]] = None,
    previous_plan: Optional[str] = None,
) -> str:
    """Build the user prompt for plan generation."""
    parts = []

    # Objective
    parts.append(f"## Objective\n{objective}")

    # Available tools
    tools_str = ", ".join(available_tools)
    parts.append(f"\n## Available Tools\n{tools_str}")

    # Trajectory (if any)
    if trajectory:
        traj_lines = []
        for i, entry in enumerate(trajectory, 1):
            action = entry.get("action", "unknown")
            result = entry.get("result", "")
            # Truncate long results
            if len(result) > 200:
                result = result[:197] + "..."
            traj_lines.append(f"{i}. [{action}] {result}")
        parts.append("\n## Execution History\n" + "\n".join(traj_lines))
    else:
        parts.append("\n## Execution History\n(No actions taken yet)")

    # Previous plan (if any)
    if previous_plan:
        parts.append(f"\n## Previous Plan\n{previous_plan}")
        parts.append(
            "\n## Task\nUpdate the plan based on progress. Mark completed steps and determine next steps."
        )
    else:
        parts.append(
            "\n## Task\nCreate a step-by-step plan to achieve the objective using only the available tools."
        )

    return "\n".join(parts)


class PlanTool(Tool):
    """
    Tool for generating execution plans by calling LLM.

    Features:
    - Calls LLM to generate plans based on objective and context
    - Takes available_tools to ensure feasible plans
    - Supports trajectory for progress-aware planning
    - Supports previous_plan for replan/update scenarios
    - Returns plan as string for agent to use

    This is a "planning sub-agent" that helps the main agent organize
    complex tasks into actionable steps.
    """

    name = "plan"
    description = """Generate or update an execution plan for the current task.

Use this tool to:
- Create a step-by-step plan at the start of a complex task
- Update the plan after making progress (replan)
- Determine next steps when unsure how to proceed

Parameters:
- objective (required): What you want to achieve
- available_tools (required): List of tool names you can use
- trajectory (optional): List of {action, result} showing what you've done
- previous_plan (optional): Your previous plan (for updating)

Returns a plan as text with numbered steps, marking completed and next steps.

Example:
plan({
    "objective": "Add a new section to the document",
    "available_tools": ["read_file", "edit_file", "list_files", "done"],
    "trajectory": [{"action": "read_file", "result": "Read main.tex"}],
    "previous_plan": "1. Read file\\n2. Edit file\\n3. Done"
})

Skip this tool for simple, single-step tasks."""

    parameters = {
        "type": "object",
        "properties": {
            "objective": {
                "type": "string",
                "description": "The goal/objective to achieve. Be specific about what needs to be done.",
            },
            "available_tools": {
                "type": "array",
                "items": {"type": "string"},
                "description": "List of tool names available for use. Plan will only use these tools.",
            },
            "trajectory": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "action": {"type": "string"},
                        "result": {"type": "string"},
                    },
                },
                "description": "Optional. List of {action, result} pairs showing execution history.",
            },
            "previous_plan": {
                "type": "string",
                "description": "Optional. Previous plan text to update based on progress.",
            },
        },
        "required": ["objective", "available_tools"],
    }

    mode = ToolMode.AGENT  # Only available in Agent mode
    executor = ExecutorType.LOCAL

    # Class-level storage for plan history (optional, for debugging/tracking)
    _plan_history: Dict[str, List[str]] = {}

    async def execute(self, params: Dict[str, Any], context: ToolContext) -> ToolResult:
        """
        Execute the plan tool - generate a plan by calling LLM.

        Args:
            params: {
                "objective": str,           # Required: goal to achieve
                "available_tools": list,    # Required: tools that can be used
                "trajectory": list,         # Optional: execution history
                "previous_plan": str,       # Optional: previous plan for update
            }
            context: Execution context with project info

        Returns:
            ToolResult with generated plan as text
        """
        objective = params.get("objective", "")
        available_tools = params.get("available_tools", [])
        trajectory = params.get("trajectory", [])
        previous_plan = params.get("previous_plan")

        # Validate required params
        if not objective:
            return ToolResult(
                success=False,
                text="Objective is required. What do you want to achieve?",
                error="Missing objective",
            )

        if not available_tools:
            return ToolResult(
                success=False,
                text="Available tools list is required. What tools can you use?",
                error="Missing available_tools",
            )

        # Emit status
        context.emit_status("Generating plan...", status="planning")

        # Build prompt
        user_prompt = build_plan_prompt(
            objective=objective,
            available_tools=available_tools,
            trajectory=trajectory,
            previous_plan=previous_plan,
        )

        # Call LLM
        try:
            client = get_llm_client()
            response = await client.chat.completions.create(
                model=config.llm_model,
                messages=[
                    {"role": "system", "content": PLAN_SYSTEM_PROMPT},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=0.3,  # Lower temperature for more focused planning
                max_tokens=1000,
            )

            plan_text = response.choices[0].message.content.strip()

            # Optionally record token usage (OSS: no payments/credits)
            await context.record_usage_from_response(
                response, action="plan_generation", tool_name="Plan"
            )

        except Exception as e:
            return ToolResult(
                success=False,
                text=f"Failed to generate plan: {str(e)}",
                error=str(e),
            )

        # Store plan in history (for debugging/tracking)
        plan_key = context.project_id or "default"
        if plan_key not in PlanTool._plan_history:
            PlanTool._plan_history[plan_key] = []
        PlanTool._plan_history[plan_key].append(plan_text)

        # Emit plan event for frontend
        is_replan = previous_plan is not None or len(trajectory) > 0
        context.emit(
            "plan",
            {
                "plan": plan_text,
                "objective": objective,
                "available_tools": available_tools,
                "is_replan": is_replan,
                "project_id": context.project_id,
            },
        )

        # Return plan to agent
        return ToolResult(
            success=True,
            text=plan_text,
            data={
                "plan": plan_text,
                "objective": objective,
                "available_tools": available_tools,
                "trajectory_length": len(trajectory),
                "is_replan": is_replan,
            },
        )

    @classmethod
    def get_plan_history(cls, project_id: str) -> List[str]:
        """Get plan history for a project (for debugging)."""
        return cls._plan_history.get(project_id, [])

    @classmethod
    def clear_history(cls, project_id: str) -> None:
        """Clear plan history for a project."""
        if project_id in cls._plan_history:
            del cls._plan_history[project_id]

    @classmethod
    def clear_all_history(cls) -> None:
        """Clear all plan history."""
        cls._plan_history.clear()


__all__ = ["PlanTool"]
