#!/usr/bin/env bash
# ==============================================================================
# Litewrite + nanobot One-Click Setup Script
# ==============================================================================
#
# This script sets up the complete Litewrite environment from scratch,
# including the nanobot Feishu bot integration.
#
# Usage:
#   ./scripts/setup.sh              # Interactive setup
#   ./scripts/setup.sh --defaults   # Use defaults (skip prompts, fill .env later)
#
# Prerequisites:
#   - Docker Desktop (or Docker Engine + Compose plugin)
#   - Internet connection (for pulling images and building)
#
# ==============================================================================

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

info()  { echo -e "${BLUE}[INFO]${NC} $*"; }
ok()    { echo -e "${GREEN}[OK]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }

banner() {
  echo
  echo -e "${CYAN}================================================================${NC}"
  echo -e "${CYAN}  Litewrite + nanobot Setup${NC}"
  echo -e "${CYAN}================================================================${NC}"
  echo
}

# --------------------------------------------------------------------------
# 1. Check prerequisites
# --------------------------------------------------------------------------
check_prerequisites() {
  info "Checking prerequisites..."

  if ! command -v docker >/dev/null 2>&1; then
    err "Docker is not installed. Please install Docker Desktop first."
    err "  https://docs.docker.com/get-docker/"
    exit 1
  fi

  if ! docker compose version >/dev/null 2>&1; then
    err "'docker compose' is not available."
    err "Please install Docker Desktop (or Docker Engine + Compose plugin)."
    exit 1
  fi

  if ! docker info >/dev/null 2>&1; then
    err "Docker daemon is not running. Please start Docker Desktop first."
    exit 1
  fi

  ok "Docker and Docker Compose are available."
}

# --------------------------------------------------------------------------
# 2. Generate secrets
# --------------------------------------------------------------------------
generate_secret() {
  python3 -c "import secrets; print(secrets.token_hex(32))" 2>/dev/null \
    || openssl rand -hex 32 2>/dev/null \
    || head -c 32 /dev/urandom | xxd -p 2>/dev/null \
    || echo "change-me-$(date +%s)"
}

# --------------------------------------------------------------------------
# 3. Create .env file
# --------------------------------------------------------------------------
setup_env() {
  local USE_DEFAULTS="${1:-false}"

  if [ -f ".env" ]; then
    warn ".env file already exists."
    if [ "$USE_DEFAULTS" = "false" ]; then
      read -rp "  Overwrite? (y/N): " answer
      if [[ ! "$answer" =~ ^[Yy]$ ]]; then
        info "Keeping existing .env file."
        return
      fi
    else
      info "Keeping existing .env file (--defaults mode)."
      return
    fi
  fi

  info "Creating .env configuration file..."

  local NEXTAUTH_SECRET
  local INTERNAL_API_SECRET
  NEXTAUTH_SECRET="$(generate_secret)"
  INTERNAL_API_SECRET="$(generate_secret)"

  local OPENROUTER_API_KEY=""
  local FEISHU_ENABLED="false"
  local FEISHU_APP_ID=""
  local FEISHU_APP_SECRET=""

  if [ "$USE_DEFAULTS" = "false" ]; then
    echo
    echo -e "${CYAN}--- AI Configuration ---${NC}"
    read -rp "  OpenRouter API Key (required for AI features, press Enter to skip): " OPENROUTER_API_KEY

    echo
    echo -e "${CYAN}--- nanobot Feishu Bot (Optional) ---${NC}"
    read -rp "  Enable Feishu bot? (y/N): " enable_feishu
    if [[ "$enable_feishu" =~ ^[Yy]$ ]]; then
      FEISHU_ENABLED="true"
      read -rp "  Feishu App ID: " FEISHU_APP_ID
      read -rp "  Feishu App Secret: " FEISHU_APP_SECRET
    fi
  fi

  cat > .env <<ENVEOF
# ==============================================================================
# Litewrite Environment Configuration
# Generated by scripts/setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# ==============================================================================

# ------------------------------------------------------------------------------
# NextAuth (session encryption)
# ------------------------------------------------------------------------------
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
NEXTAUTH_URL=http://localhost:3000
NEXT_PUBLIC_SITE_URL=http://localhost:3000

# ------------------------------------------------------------------------------
# Internal service auth (Next.js <-> ai-server / ws-server / nanobot)
# ------------------------------------------------------------------------------
INTERNAL_API_SECRET=${INTERNAL_API_SECRET}

# ------------------------------------------------------------------------------
# WebSocket (client connection URL)
# ------------------------------------------------------------------------------
NEXT_PUBLIC_WS_URL=ws://localhost:1234

# ------------------------------------------------------------------------------
# AI providers (OpenRouter)
# ------------------------------------------------------------------------------
OPENROUTER_API_KEY=${OPENROUTER_API_KEY}

# ------------------------------------------------------------------------------
# nanobot (Feishu bot integration)
# ------------------------------------------------------------------------------
FEISHU_ENABLED=${FEISHU_ENABLED}
FEISHU_APP_ID=${FEISHU_APP_ID}
FEISHU_APP_SECRET=${FEISHU_APP_SECRET}
# Your Litewrite user UUID (will be set after first user registration)
NANOBOT_DEFAULT_LITEWRITE_USER_ID=
ENVEOF

  ok ".env file created."

  if [ -z "$OPENROUTER_API_KEY" ]; then
    warn "OPENROUTER_API_KEY is not set. AI features and nanobot will not work."
    warn "Edit .env and add your API key before starting."
  fi
}

# --------------------------------------------------------------------------
# 4. Build and start services
# --------------------------------------------------------------------------
build_and_start() {
  info "Building Docker images (first run takes 10-20 minutes)..."
  echo

  docker compose build

  echo
  ok "All images built successfully."

  info "Starting services..."
  docker compose up -d

  echo
  ok "All services started."
}

# --------------------------------------------------------------------------
# 5. Wait for services to be healthy
# --------------------------------------------------------------------------
wait_for_services() {
  info "Waiting for services to be ready..."

  local max_wait=120
  local elapsed=0

  # Wait for web
  while [ $elapsed -lt $max_wait ]; do
    if curl -sf http://localhost:3000/api/auth/session >/dev/null 2>&1; then
      break
    fi
    sleep 3
    elapsed=$((elapsed + 3))
    printf "."
  done
  echo

  if [ $elapsed -ge $max_wait ]; then
    warn "Web service did not become healthy within ${max_wait}s."
    warn "Check logs: docker compose logs web"
  else
    ok "Web service is ready."
  fi
}

# --------------------------------------------------------------------------
# 6. Print summary
# --------------------------------------------------------------------------
print_summary() {
  echo
  echo -e "${CYAN}================================================================${NC}"
  echo -e "${CYAN}  Setup Complete!${NC}"
  echo -e "${CYAN}================================================================${NC}"
  echo
  echo -e "  ${GREEN}Litewrite App${NC}       http://localhost:3000"
  echo -e "  ${GREEN}WebSocket${NC}           ws://localhost:1234"
  echo -e "  ${GREEN}AI Server${NC}           http://localhost:6612/health"
  echo -e "  ${GREEN}Compile Server${NC}      http://localhost:3002/health"
  echo -e "  ${GREEN}MinIO Console${NC}       http://localhost:9001  (minioadmin/minioadmin)"
  echo

  if grep -q "FEISHU_ENABLED=true" .env 2>/dev/null; then
    echo -e "  ${GREEN}nanobot (Feishu)${NC}    Running (check: docker logs litewrite-nanobot)"
  else
    echo -e "  ${YELLOW}nanobot (Feishu)${NC}    Disabled (set FEISHU_ENABLED=true in .env)"
  fi

  echo
  echo -e "${BLUE}Next steps:${NC}"
  echo "  1. Open http://localhost:3000 and register an account"
  echo "  2. Create a LaTeX project and start writing"
  echo
  echo "  To enable nanobot Feishu bot:"
  echo "  1. Set FEISHU_ENABLED=true, FEISHU_APP_ID, FEISHU_APP_SECRET in .env"
  echo "  2. Set NANOBOT_DEFAULT_LITEWRITE_USER_ID to your user UUID"
  echo "  3. Run: docker compose up -d nanobot"
  echo
  echo "  See nanobot/DEPLOYMENT.md for detailed nanobot configuration guide."
  echo
  echo -e "${BLUE}Useful commands:${NC}"
  echo "  docker compose ps                  # Check service status"
  echo "  docker compose logs -f web         # Follow web logs"
  echo "  docker compose logs -f nanobot     # Follow nanobot logs"
  echo "  docker compose down                # Stop all services"
  echo "  docker compose up -d --build       # Rebuild and restart"
  echo
}

# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------
main() {
  local USE_DEFAULTS="false"
  if [ "${1:-}" = "--defaults" ]; then
    USE_DEFAULTS="true"
  fi

  banner
  check_prerequisites
  setup_env "$USE_DEFAULTS"
  build_and_start
  wait_for_services
  print_summary
}

main "$@"
